User authentification
JavierAybar/Full_Stack_Capstone_Front_End pull request #3
Opened 2023-12-02 10:23 UTC by everinurmind

In this pull request, I have implemented proper user authentication from the front end to the server. Here are the **key** changes and updates made:

**Redux Integration:** I integrated Redux into the application to manage the state related to user authentication. This includes the creation of an authSlice to handle user authentication actions and a store configuration in src/redux/store.js.

**Authentication Service:** I created an AuthService module (src/services/AuthService.js) to handle user login, registration, and logout operations. This service communicates with the server API endpoints for authentication.

**User Login Page:** Implemented a user login page (src/pages/Login.jsx) where users can enter their email and password to authenticate. Input validation is also included to ensure the entered email is valid.

**User Registration Page:** Created a user registration page (src/pages/Registration.jsx) where users can register by providing their email, password, and password confirmation. Input validation is implemented for user convenience.

**Logout Functionality:** Implemented a logout page (src/pages/Logout.jsx) that logs the user out by communicating with the server to invalidate the authentication token.

**Protected Routes:** Configured protected routes in src/App.js by using the isAuthenticated attribute to restrict access to authenticated users only. This ensures that unauthenticated users are redirected appropriately.

**Redux Toolkit:** Utilized Redux Toolkit for efficient state management and asynchronous actions using createAsyncThunk.

These changes ensure that user authentication is handled securely and efficiently, enhancing the overall functionality of the application.

2023-12-02 11:10 UTC, everinurmind commented
#11

2023-12-03 23:59 UTC, Abdelaziz-Mahdi commented on src/services/AuthService.js
> +const API_URL = 'http://localhost:3000/api/v1';
Hello @everinurmind 
kindly fix the back-end URL as it doesn't include /api/v1
Thanks

2023-12-04 00:10 UTC, Abdelaziz-Mahdi requested changes
Hello @everinurmind 
### Changes requiered
while you made a great effort small changes are required

- [ ] Kindly check back-end routes for example by running the following command `rails routes` and fix all invalid URLs, I have mentioned some of them below.

* Please note that I was able to review only for AuthServices.js

2023-12-04 00:10 UTC, Abdelaziz-Mahdi commented on src/services/AuthService.js
> +};
also, sign-in and sign-out should be something like  ${API_URL}/signin` 
Kindly check back-end routes and correct similar cases

2023-12-04 00:10 UTC, Abdelaziz-Mahdi commented on src/services/AuthService.js
> +const API_URL = 'http://localhost:3000/api/v1';
Hello @everinurmind
kindly fix the back-end URL as it doesn't include /api/v1
Thanks

2023-12-05 20:02 UTC, JavierAybar commented
Hello @everinurmind 

- Please remember to add the username input on registration page, the user should have `username`, `email`, `password`.
Once you make this change and mege it into dev branch, I'll be able to test it well with the rest of the code

2023-12-05 22:06 UTC, everinurmind commented
@JavierAybar hi, I just did the corrections that you requested. Could you please check it, and merge it if there is no correction needed anymore? Thank you very much!

2023-12-06 02:41 UTC, JavierAybar commented
Hello @everinurmind 

Everything looks fine! I need to check it later when the other pr will merge it.
Now I'm going to do the merge.

2023-12-06 02:41 UTC, merged